name: Build EfektyGracza

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Compile Plugin
      run: |
        mkdir -p build/classes
        javac -d build/classes src/main/java/pl/banknotmc/efekty/EfektyGracza.java
        cd build/classes
        jar cf ../../EfektyGracza.jar pl
    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
        name: EfektyGracza
        path: EfektyGracza.jar